config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "https://locavore-jacklinton.c9users.io"
  
  resources :contacts, only: [:new, :create]

  devise_for :users, :controllers => { registrations: 'registrations' }

  root "home#index"
    resources :users, only: [:show, :update]
    resources :maps
    resources :listings
    resources :pictures
    resources :items
    resources :invites
    resources :events

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/listing.rb
class Listing < ApplicationRecord
    attr_accessor :address
    
    belongs_to :user
    has_many :pictures
    
    
    geocoded_by :address, latitude: :lat, longitude: :lng   # can also be an IP address
    after_validation :geocode        # auto-fetch coordinates
    
    reverse_geocoded_by :lat, :lng
    after_validation :reverse_geocode
    
    acts_as_mappable
    
    has_attached_file :picture,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
  
  
end

app/controllers/listing_controller.rb
class ListingController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    before_action :set_listing, only: [:update, :show, :edit]
    
    def index
        @listings = Listing.all
    end
    
    def new
        @listing = Listing.new()
    end
    
    def edit
        
    end
    
    def update
        if @listing.update_attributes(title: listing_params[:title],
                lat: listing_params[:lat],
                lon: listing_params[:lon],
                category: listing_params[:category],
                acc_cash: listing_params[:acc_cash],
                acc_trade: listing_params[:acc_trade],
                description: listing_params[:description],
                wants: listing_params[:wants],
                quantity: listing_params[:quantity],
                harvest_date: listing_params[:harvest_date],
                exp_date: listing_params[:exp_date],
                picture: listing_params[:picture])
            flash[:notice] = "Successfully updated your listing!"
            redirect_to listing_path(@listing)
        else
            flash[:alert] = "The was a problem updating your listing information, please try again."
            render :edit
        end
    end
    
    def show
        
    end
    
    def create
        @listing = current_user.listings.new
        @listing.update_attributes(title: listing_params[:title],
                lat: listing_params[:lat],
                lon: listing_params[:lon],
                category: listing_params[:category],
                acc_cash: listing_params[:acc_cash],
                acc_trade: listing_params[:acc_trade],
                description: listing_params[:description],
                wants: listing_params[:wants],
                quantity: listing_params[:quantity],
                harvest_date: listing_params[:harvest_date],
                exp_date: listing_params[:exp_date],
                picture: listing_params[:picture])
        if @listing.save
            flash[:notice] = "You have successfully created a new listing!"
            redirect_to listing_path(@listing)
        else
            flash[:alert] = "There was a problem creating your listing. Please try again."
            render :new
        end
    end
end

private

def set_listing
    @listing = Listing.find(params[:id])
end

def listing_params
    params.require(:listing).permit(:title, :lat, :lon, :category, :acc_cash, :acc_trade, :description, :wants, :quantity, :harvest_date, :exp_date, :picture)
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    before_action :set_listing, only: [:update, :show, :edit]
    
    def index
        @listings = Listing.all
        @user = current_user
        @listingshash = Gmaps4rails.build_markers(@listings) do |listing, marker|
          marker.lat listing.lat
          marker.lng listing.lng
          marker.title listing.title
        end
    end
    
    def new
        @listing = Listing.new()
    end
    
    def edit
        
    end
    
    def update
        if @listing.update_attributes(title: listing_params[:title],
                address: listing_params[:address],
                lat: listing_params[:lat],
                lng: listing_params[:lng],
                category: listing_params[:category],
                acc_cash: listing_params[:acc_cash],
                acc_trade: listing_params[:acc_trade],
                description: listing_params[:description],
                wants: listing_params[:wants],
                quantity: listing_params[:quantity],
                harvest_date: listing_params[:harvest_date],
                exp_date: listing_params[:exp_date],
                picture: listing_params[:picture])
            flash[:notice] = "Successfully updated your listing!"
            redirect_to listing_path(@listing)
        else
          flash[:alert] = "There was a problem updating your listing information, please try again."
          render :edit
        end
    end
    
    def show
        @user = current_user
    end
    
    def create
        @user = current_user
        @listing = Listing.new
        @listing.update_attributes(user_id: @user.id,
                title: listing_params[:title],
                address: listing_params[:address],
                lat: listing_params[:lat],
                lng: listing_params[:lng],
                category: listing_params[:category],
                acc_cash: listing_params[:acc_cash],
                acc_trade: listing_params[:acc_trade],
                description: listing_params[:description],
                wants: listing_params[:wants],
                quantity: listing_params[:quantity],
                harvest_date: listing_params[:harvest_date],
                exp_date: listing_params[:exp_date],
                picture: listing_params[:picture])
        if @listing.save
            flash[:notice] = "You have successfully created a new listing!"
            redirect_to listing_path(@listing)
        else
            flash[:alert] = "There was a problem creating your listing. Please try again."
            render :new
        end
    end
    
    def delete
        @listing.destroy
    end
end

private

def set_listing
    @listing = Listing.find(params[:id])
end

def listing_params
    params.require(:listing).permit(:title, :address, :lat, :lng, :category, :acc_cash, :acc_trade, :description, :wants, :quantity, :harvest_date, :exp_date, :picture)
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listings/ListingTable.html.erb
 <div class="container-fluid">     
    <h1>Listings Table</h1>    
        <table id="listings" class="display responsive no-wrap" width="100%">
            <thead>
                <tr>
                    <th>Picture</th>
                    <th>Title</th>
                    <th>Distance</th>
                    <th>Description</th>
                    <th>Accepting Cash?</th>
                    <th>Accepting Trade?</th>
                    <th>Wants</th>
                    <th>Link</th>
                </tr>
            </thead>
            <tbody>
                <% @listings.each do |l| %>
                    <tr>
                        <td><%= image_tag l.picture:thumb %></td>
                        <td><%= l.title %></td>
                        <td>distance</td>
                        <td><%= l.description %></td>
                        <td><%= l.acc_cash %></td>
                        <td><%= l.acc_trade %></td>
                        <td><%= l.wants %></td>
                        <td><%= link_to "Read more", listing_path(l) %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
</div>  

app/views/listings/_formeditlisting.html.erb
<%= simple_form_for @listing do |f| %>
    <%= f.input :title, required:true, input_html: { value: @listing.title } %>
    <%= f.input :address, required:true, input_html: { class: "address" } %>
    <%= f.input :category, input_html: { value: @listing.category } %>
    <%= f.input :acc_cash, input_html: { value: @listing.acc_cash } %>
    <%= f.input :acc_trade, input_html: { value: @listing.acc_trade } %>
    <%= f.input :description, input_html: { value: @listing.description } %>
    <%= f.input :wants, input_html: { value: @listing.wants} %>
    <%= f.input :quantity, { value: @listing.quantity} %>
    <%= f.input :harvest_date, as: :date, html5: true, input_html: { value: @listing.harvest_date } %>
    <%= f.input :exp_date, as: :date, html5: true, input_html: { value: @listing.exp_date } %>
    <%= f.input :picture, as: :file %>
    <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/listings/_formlisting.html.erb
<%= simple_form_for @listing do |f| %>
    <%= f.input :title, required:true  %>
    <%= f.input :address, required:true, input_html: { class: "address" } %>
    <%= f.input :category %>
    <%= f.input :acc_cash %>
    <%= f.input :acc_trade %>
    <%= f.input :description %>
    <%= f.input :wants %>
    <%= f.input :quantity %>
    <%= f.input :harvest_date, as: :date, html5: true %>
    <%= f.input :exp_date, as: :date, html5: true %>
    <%= f.input :picture, as: :file %>
    <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/listings/edit.html.erb
<%= render "listings/formeditlisting" %>
<%= button_to "Back to Listing", listing_path(@listing), method: :get, class: 'btn btn-back' %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <% if user_signed_in? %>
                <li class="sidebar-brand">
                </li>
                <li>
                    <%= image_tag current_user.avatar:thumbnail %>
                </li>
                <li>
                    <%= link_to "Hello, #{current_user.username}", "#" %>
                </li>
                <li>
                    <%= link_to "Inbox", mailbox_inbox_path %>
                </li>
                <li>
                    <a href="/events/index">Events</a>
                </li>
                <li>
                    <%= link_to "Create New Listing", new_listing_path %>
                </li>
                <li>
                    <%= link_to "Create New Event", new_event_path %>
                </li>
                <% else %>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                        
                        
                        
                        
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>

</html>

app/views/listings/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <% if user_signed_in? %>
                <li class="sidebar-brand">
                </li>
                <li>
                    <%= image_tag current_user.avatar:thumbnail %>
                </li>
                <li>
                    <%= link_to "Hello, #{current_user.username}", "#" %>
                </li>
                <li>
                    <%= link_to "Inbox", mailbox_inbox_path %>
                </li>
                <li>
                    <a href="/events/index">Events</a>
                </li>
                <li>
                    <%= link_to "Create New Listing", new_listing_path %>
                </li>
                <li>
                    <%= link_to "Create New Event", new_event_path %>
                </li>
                
                <% else %>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                        <div>     
                            <h1>Listings Table</h1>    
                                <table id="listings" class="display responsive no-wrap table table-striped" classspacing="0" width="100%">
                                    <thead class="thead-default">
                                        <tr>
                                            <th>Picture</th>
                                            <th>Title</th>
                                            <th>Distance</th>
                                            <th>Description</th>
                                            <th>Accepting Cash?</th>
                                            <th>Accepting Trade?</th>
                                            <th>Wants</th>
                                            <th>Link</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @listings.each do |l| %>
                                            <tr>
                                                <td><%= image_tag l.picture:thumb %></td>
                                                <td><%= l.title %></td>
                                                <td>distance</td>
                                                <td><%= l.description %></td>
                                                <td><%= l.acc_cash %></td>
                                                <td><%= l.acc_trade %></td>
                                                <td><%= l.wants %></td>
                                                <td><%= link_to "Read more", listing_path(l) %></td>
                                            </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                        </div>  
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                        <div class="container-fluid">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div style='width: 800px;'>
                                          <div id="map" style='width: 800px; height: 400px;'>
                                              <script>handler = Gmaps.build('Google');
                                                        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                                                          markers = handler.addMarkers(
                                                        
                                                        <%= raw @listingshash.to_json %>
                                                      );
                                                      handler.bounds.extendWith(markers);
                                                      handler.bounds.extendWith(markers);
                                                      handler.map.centerOn({ lat: <%= @user.lat %>, lng: <%= @user.lng %> })
                                                    });</script>
                                          </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>

</html>

app/views/listings/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <% if user_signed_in? %>
                <li class="sidebar-brand">
                </li>
                <li>
                    <%= image_tag current_user.avatar:thumbnail %>
                </li>
                <li>
                    <%= link_to "Hello, #{current_user.username}", "#" %>
                </li>
                <li>
                    <%= link_to "Inbox", mailbox_inbox_path %>
                </li>
                <li>
                    <a href="/events/index">Events</a>
                </li>
                <li>
                    <%= link_to "Create New Listing", new_listing_path %>
                </li>
                <li>
                    <%= link_to "Create New Event", new_event_path %>
                </li>
                <% else %>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                        <%= render "listings/formlisting" %>
                        
                        
                        
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>

</html>

app/views/listings/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <% if user_signed_in? %>
                <li class="sidebar-brand">
                </li>
                <li>
                    <%= image_tag current_user.avatar :thumbnail %>
                </li>
                <li>
                    <%= link_to "Hello, #{current_user.username}", "#" %>
                </li>
                <li>
                    <%= link_to "Inbox", mailbox_inbox_path %>
                </li>
                <li>
                    <a href="/events/index">Events</a>
                </li>
                <li>
                    <%= link_to "Create New Listing", new_listing_path %>
                </li>
                <li>
                    <%= link_to "Create New Event", new_event_path %>
                </li>
                <% else %>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                        
                        
                        <h1>Title: <%= @listing.title %></h1>
                        <br>
                        <br>
                        <% @user = User.find(@listing.user_id) %>
                        <p>Created by: <%= @user.username %></p>
                        <%= button_to "Email Owner of This Listing", new_conversation_path, method: :get %>
                        <br>
                        <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@listing.lat},#{@listing.lng}&markers=#{@listing.lat},#{@listing.lng}&zoom=15&size=640x400",
                                      class: 'img-fluid img-rounded', alt: "#{@listing.title} on the map"%>
                        <br>
                        <p><%= @listing.address %></p>
                        <p>Category: <%= @listing.category %></p>
                        <br>
                        <p>Description: <%= @listing.description %></p>
                        <br>
                        <p>Wants: <%= @listing.wants %></p>
                        <br>
                        <p>Quantity: <%= @listing.quantity %></p>
                        <br>
                        <p>Harvest Date: <%= @listing.harvest_date %></p>
                        <br>
                        <p>Listing Expiration: <%= @listing.exp_date %></p>
                        <br>
                        <p><%= image_tag @listing.picture %> </p>
                        
                        <%= button_to "Edit Listing", edit_listing_path(@listing), method: :get, class: "btn btn-primary" %>
                        <%= button_to "Delete Listing", listing_path(@listing), method: :delete, class: "btn btn-warning" %>
                        
                                                
                        
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>

</html>