config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "https://locavore-jacklinton.c9users.io"
  
  resources :contacts, only: [:new, :create]

  devise_for :users, :controllers => { registrations: 'registrations' }

  root "home#index"
    resources :users, only: [:show, :update]
    resources :maps
    resources :listings
    resources :pictures
    resources :items
    resources :invites
    resources :events

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, 			:validate => true
	attribute :email,			:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message, 	:validate => true
	attribute "nickname", "captcha" => true

	def headers 
		{
			:sibject => "Contact Form",
			:to => "jcl9595@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/event.rb
class Event < ApplicationRecord
    attr_accessor :address
    
    belongs_to :user
    has_many :items
    has_many :photos
    has_many :invites
    
    geocoded_by :address, latitude: :lat, longitude: :lng   # can also be an IP address
    after_validation :geocode         # auto-fetch coordinates
    
    reverse_geocoded_by :lat, :lng
    after_validation :reverse_geocode
    
    acts_as_mappable
    
    has_attached_file :photo,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
    belongs_to :event
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :event
    has_one :user
end

app/models/listing.rb
class Listing < ApplicationRecord
    attr_accessor :address
    
    belongs_to :user
    has_many :pictures
    
    
    geocoded_by :address, latitude: :lat, longitude: :lng   # can also be an IP address
    after_validation :geocode        # auto-fetch coordinates
    
    reverse_geocoded_by :lat, :lng
    after_validation :reverse_geocode
    
    acts_as_mappable
    
    has_attached_file :picture,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
  
  
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_one :user
    belongs_to :event or belongs_to :listing
    
    
    has_attached_file :file,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    attr_accessor :address
    
    geocoded_by :address, latitude: :lat, longitude: :lng   # can also be an IP address
    after_validation :geocode        # auto-fetch coordinates
    
    reverse_geocoded_by :lat, :lng
    after_validation :reverse_geocode
    
    acts_as_mappable
    
    acts_as_messageable
    
    def mailboxer_name
      self.username
    end

    def mailboxer_email(object)
      self.email
    end
    
    has_attached_file :avatar,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "shatner.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
         
   has_many :invites
   has_many :items
   has_many :listings
   has_many :events
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!


    def new
    end
    
      def create
        recipients = User.where(id: conversation_params[:recipients])
        conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
        flash[:success] = "Your message was successfully sent!"
        redirect_to conversation_path(conversation)
      end
    
      def show
        @receipts = conversation.receipts_for(current_user)
        # mark conversation as read
        conversation.mark_as_read(current_user)
      end
      
      def reply
        current_user.reply_to_conversation(conversation, message_params[:body])
        flash[:notice] = "Your reply message was successfully sent!"
        redirect_to conversation_path(conversation)
      end
      
      def trash
        conversation.move_to_trash(current_user)
        redirect_to mailbox_inbox_path
      end
    
      def untrash
        conversation.untrash(current_user)
        redirect_to mailbox_inbox_path
      end

    
    
      private
    
      def conversation_params
        params.require(:conversation).permit(:subject, :body,recipients:[])
      end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @usershash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.lat
      marker.lng user.lng
      marker.title user.username
    end
    @listings = Listing.all
    @listingshash = Gmaps4rails.build_markers(@listings) do |listing, marker|
      marker.lat listing.lat
      marker.lng listing.lng
      marker.title listing.title
    end
    @events = Event.all
    @eventshash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.lat
      marker.lng event.lng
      marker.title event.name
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
      case level.to_sym
        when :notice then "alert alert-success"
        when :info then "alert alert-info"
        when :alert then "alert alert-danger"
        when :warning then "alert alert-warning"
      end
    end
    
    def active_page(active_page)
      @active == active_page ? "active" : ""
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
    def unread_messages_count
      # how to get the number of unread messages for the current user
      # using mailboxer
      # mailbox.inbox(:unread => true).count(:id, :distinct => true)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/conversations/_conversation.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.username, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.username %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <% if user_signed_in? %>
                <li class="sidebar-brand">
                </li>
                <li>
                    <%= image_tag current_user.avatar:thumbnail %>
                </li>
                <li>
                    <%= link_to "Hello, #{current_user.username}", "#" %>
                </li>
                <li>
                    <%= link_to "Inbox", mailbox_inbox_path %>
                </li>
                <li>
                    <a href="events/index">Events</a>
                </li>
                <li>
                    <%= link_to "Create New Listing", new_listing_path %>
                </li>
                <li>
                    <%= link_to "Create New Event", new_event_path %>
                </li>
                <% else %>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>
                        
                        
                        
                        
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>

</html>

app/views/conversations/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <% if user_signed_in? %>
                <li class="sidebar-brand">
                </li>
                <li>
                    <%= image_tag current_user.avatar:thumbnail %>
                </li>
                <li>
                    <%= link_to "Hello, #{current_user.username}", "#" %>
                </li>
                <li>
                    <%= link_to "Inbox", mailbox_inbox_path %>
                </li>
                <li>
                    <a href="events/index">Events</a>
                </li>
                <li>
                    <%= link_to "Create New Listing", new_listing_path %>
                </li>
                <li>
                    <%= link_to "Create New Event", new_event_path %>
                </li>
                <% else %>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                        <div class="row">
                          <div class="spacer"></div>
                          <div class="col-md-12">
                            <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
                            <div class="spacer"></div>
                          </div>
                        
                          <div class="col-md-4">
                            <div class="panel panel-default">
                              <div class="panel-body">
                                <%= render 'mailbox/folders' %>
                              </div>
                            </div>
                          </div>
                        
                          <div class="col-md-8">
                            <div class="panel panel-default">
                              <div class="panel-body">
                                <%= render partial: 'messages' %>
                              </div>
                              <div class="panel-footer">
                                <!-- Reply Form -->
                                <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
                                    <div class="form-group">
                                      <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
                                    </div>
                                    <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
                                <% end %>
                                <div class="clearfix"></div>
                              </div>
                            </div>
                          </div>
                        
                        </div>
                        
                        
                        
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>

</html>