config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "https://locavore-jacklinton.c9users.io"
  
  resources :contacts, only: [:new, :create]

  devise_for :users, :controllers => { registrations: 'registrations' }

  root "home#index"
    resources :users, only: [:show, :update]
    resources :maps
    resources :listings
    resources :pictures
    resources :items
    resources :invites
    resources :events

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, 			:validate => true
	attribute :email,			:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message, 	:validate => true
	attribute "nickname", "captcha" => true

	def headers 
		{
			:sibject => "Contact Form",
			:to => "jcl9595@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/event.rb
class Event < ApplicationRecord
    attr_accessor :address
    
    belongs_to :user
    has_many :items
    has_many :photos
    has_many :invites
    
    geocoded_by :address, latitude: :lat, longitude: :lng   # can also be an IP address
    after_validation :geocode         # auto-fetch coordinates
    
    reverse_geocoded_by :lat, :lng
    after_validation :reverse_geocode
    
    acts_as_mappable
    
    has_attached_file :photo,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
    belongs_to :event
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :event
    has_one :user
end

app/models/listing.rb
class Listing < ApplicationRecord
    attr_accessor :address
    
    belongs_to :user
    has_many :pictures
    
    
    geocoded_by :address, latitude: :lat, longitude: :lng   # can also be an IP address
    after_validation :geocode        # auto-fetch coordinates
    
    reverse_geocoded_by :lat, :lng
    after_validation :reverse_geocode
    
    acts_as_mappable
    
    has_attached_file :picture,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
  
  
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_one :user
    belongs_to :event or belongs_to :listing
    
    
    has_attached_file :file,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    attr_accessor :address
    
    geocoded_by :address, latitude: :lat, longitude: :lng   # can also be an IP address
    after_validation :geocode        # auto-fetch coordinates
    
    reverse_geocoded_by :lat, :lng
    after_validation :reverse_geocode
    
    acts_as_mappable
    
    acts_as_messageable
    
    def mailboxer_name
      self.username
    end

    def mailboxer_email(object)
      self.email
    end
    
    has_attached_file :avatar,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    default_url: "shatner.png",
        :storage => :s3,
        :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
        s3_region: ENV["AWS_REGION"]
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def s3_credentials
    {:bucket => "railsblogbucket", :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
         
   has_many :invites
   has_many :items
   has_many :listings
   has_many :events
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @usershash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.lat
      marker.lng user.lng
      marker.title user.username
    end
    @listings = Listing.all
    @listingshash = Gmaps4rails.build_markers(@listings) do |listing, marker|
      marker.lat listing.lat
      marker.lng listing.lng
      marker.title listing.title
    end
    @events = Event.all
    @eventshash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.lat
      marker.lng event.lng
      marker.title event.name
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
      case level.to_sym
        when :notice then "alert alert-success"
        when :info then "alert alert-info"
        when :alert then "alert alert-danger"
        when :warning then "alert alert-warning"
      end
    end
    
    def active_page(active_page)
      @active == active_page ? "active" : ""
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
    def unread_messages_count
      # how to get the number of unread messages for the current user
      # using mailboxer
      # mailbox.inbox(:unread => true).count(:id, :distinct => true)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_bar.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Locavore Home", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Listings", listings_path %></li>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Map", maps_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">

            <% if current_user %>
              <li><%= link_to current_user.username, user_path(current_user) %> </li>
              <li><%= link_to "Sign out", destroy_user_session_path,  method: :DELETE %></li>

            <% else %>

              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path  %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/_navbar.html.erb
<body>
  <!-- NAVBAR ================================================== -->


          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            <li><%= link_to "Crop sharing", root_path %></li>
              
              <li><a href="#">Blog</a></li>
              <li><a href="#about">About Us</a></li>
              <li><a href="#contact">Contact Us</a></li>
              <li><a href="#help">Help</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign Up<b class="caret"></b></a>
                <ul class="dropdown-menu">
                 <li>
                  <div class="navbar-content">
                    <div class="row">
                      <div class="col-md-12">
                        <h3>Sign Up</h3>

                        <%= form_tag("/users", html: { class: "form-signup"}) do %>

                        <%= text_field_tag :email, nil ,class: 'form-control', id: 'inputEmail', placeholder: 'Email address' %>

                        <%= password_field_tag :password, nil, class: 'form-control', id: 'inputPassword', placeholder: 'Password' %>

                        <%= password_field_tag :password_confirmation, nil, class: "form-control", id: "inputPassword", placeholder: 'Confirmation' %>

                        <%= submit_tag "Sign up", :class => 'btn btn-sm btn-primary' %>
                        <% end %>
<!-- 
                                        <label for="inputEmail" class="sr-only">User Name</label>
                                        <input type="text" id="inputName" class="form-control" placeholder="User Name" required autofocus>
                                    
                                      
                                    
                                        <label for="inputPassword" class="sr-only">Confirm your Password</label>
                                        <input type="password" id="inputPassword" class="form-control" placeholder="Confirm Your Password" required>
                                    
                                        <div class="checkbox">
                                          <label><input type="checkbox" value="remember-me"> Remember me</label>
                                        </div>
                                        <div class="navbar-footer-content" align="center">
                                          <input type="reset" class="btn btn btn-sm btn-info" type="reset" value="Reset Button">
                                          <a class="btn btn-sm btn-primary" href="post-login-blog.html" role="button">Sign Up</a>
                                        </div> -->
                                      </div>
                                    </div>
                                  </div>
                                </li>
                              </ul>
                            </li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                   <li>
                    <div class="navbar-content">
                      <div class="row">
                        <div class="col-md-12">
                          <form class="form-signin">
                            <h3>Sign In</h3>
                            <label for="inputEmail" class="sr-only">Email address</label>
                            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                            <label for="inputPassword" class="sr-only">Password</label>
                            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                            <div class="checkbox">
                              <label>
                                <input type="checkbox" value="remember-me"> Remember me
                              </label>
                            </div>
                            <div class="navbar-footer-content" align="center">
                              <input type="reset" class="btn btn btn-sm btn-info" type="reset" value="Reset Button">
                              <a class="btn btn-sm btn-primary" href="post-login-blog.html" role="button">Sign In</a>
                            </div>
                          </form>
                        </div>
              <% else %>
                <li> 
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                </li>
              <% end %>
              </div>

app/views/layouts/_navbar_problem.html.erb
<body>
  <!-- NAVBAR ================================================== -->


          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            <li><%= link_to "Crop sharing", root_path %></li>
              
              <li><a href="#">Blog</a></li>
              <li><a href="#about">About Us</a></li>
              <li><a href="#contact">Contact Us</a></li>
              <li><a href="#help">Help</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
              <li class="dropdown">
              <%= link_to "Sign me up", new_user_session_path %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign Up<b class="caret"></b></a>
                <ul class="dropdown-menu">
                 <li>
                  <div class="navbar-content">
                    <div class="row">
                      <div class="col-md-12">
                        <h3>Sign Up</h3>

<!--                         <%= form_tag("/users", html: { class: "form-signup"}) do %>

                        <%= text_field_tag :email, nil ,class: 'form-control', id: 'inputEmail', placeholder: 'Email address' %>

                        <%= password_field_tag :password, nil, class: 'form-control', id: 'inputPassword', placeholder: 'Password' %>

                        <%= password_field_tag :password_confirmation, nil, class: "form-control", id: "inputPassword", placeholder: 'Confirmation' %>

                        <%= submit_tag "Sign up", :class => 'btn btn-sm btn-primary' %>
                        <% end %>
 --><!-- 
                                        <label for="inputEmail" class="sr-only">User Name</label>
                                        <input type="text" id="inputName" class="form-control" placeholder="User Name" required autofocus>
                                    
                                      
                                    
                                        <label for="inputPassword" class="sr-only">Confirm your Password</label>
                                        <input type="password" id="inputPassword" class="form-control" placeholder="Confirm Your Password" required>
                                    
                                        <div class="checkbox">
                                          <label><input type="checkbox" value="remember-me"> Remember me</label>
                                        </div>
                                        <div class="navbar-footer-content" align="center">
                                          <input type="reset" class="btn btn btn-sm btn-info" type="reset" value="Reset Button">
                                          <a class="btn btn-sm btn-primary" href="post-login-blog.html" role="button">Sign Up</a>
                                        </div> -->
                                      </div>
                                    </div>
                                  </div>
                                </li>
                              </ul>
                            </li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                   <li>
                    <div class="navbar-content">
                      <div class="row">
                        <div class="col-md-12">
                          <form class="form-signin">
                            <h3>Sign In</h3>
                            <label for="inputEmail" class="sr-only">Email address</label>
                            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                            <label for="inputPassword" class="sr-only">Password</label>
                            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                            <div class="checkbox">
                              <label>
                                <input type="checkbox" value="remember-me"> Remember me
                              </label>
                            </div>
                            <div class="navbar-footer-content" align="center">
                              <input type="reset" class="btn btn btn-sm btn-info" type="reset" value="Reset Button">
                              <a class="btn btn-sm btn-primary" href="post-login-blog.html" role="button">Sign In</a>
                            </div>
                          </form>
                        </div>
              <% else %>
                <li> 
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                </li>
              <% end %>
              </div>

app/views/layouts/_sidebar.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <% if user_signed_in? %>
                <li class="sidebar-brand">
                </li>
                <li>
                    <%= image_tag current_user.avatar %>
                </li>
                <li>
                    <%= link_to "Hello, #{current_user.username}", "#" %>
                </li>
                <li>
                    <%= link_to "Inbox", mailbox_inbox_path %>
                </li>
                <li>
                    <a href="/events/index">Events</a>
                </li>
                <% else %>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                        
                        
                        
                        
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>

</html>

app/views/layouts/_test.html.erb
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
							<%= link_to "register me", new_user_registration_path  %>
								<a href="#" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" action="http://phpoll.com/login/process" method="post" role="form" style="display: block;">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group text-center">
										<input type="checkbox" tabindex="3" class="" name="remember" id="remember">
										<label for="remember"> Remember Me</label>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="http://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
										</div>
									</div>
								</form>
								<form id="register-form" action="http://phpoll.com/register/process" method="post" role="form" style="display: none;">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Cropsharing</title>
	<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    "https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css" %>
    <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js" %>
    <%= javascript_include_tag "https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js" %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GMAPS_API_KEY']%>&libraries=places"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.4/dist/typeahead.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead-addresspicker/0.1.4/typeahead-addresspicker.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script> 
	<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>


<body>
	<%= render 'layouts/bar' %>
	
	<% flash.each do |key, value| %>
    	<div class="text-center <%= flash_class(key) %>">
      		<%= value %>
    	</div>
	<% end %>


		<%= yield %>

</body>
</html>